import { createHash, randomUUID } from "node:crypto";
import type { TenantRequestContext } from "../../../modules/runtime-manifest/model.js";
import type { ConfigInput, Page, PageRequest } from "../../../modules/system/application/dto.js";
import type { SystemConfig } from "../../../modules/system/domain/models.js";
import type { SqlPool } from "../client.js";
import { PostgresRepository, cursorOffset, timestamp, toPage } from "./support.js";
import { mapConfig } from "./mappers.js";
import type { Row } from "./support.js";

export class PostgresConfigRepository extends PostgresRepository {
  public constructor(pool: SqlPool) { super(pool); }
  public async list(context: TenantRequestContext, request: PageRequest): Promise<Page<SystemConfig>> { return this.withTransaction(async (client) => { const offset = cursorOffset(request); const result = await client.query<Row>("SELECT id, tenant_id, module_key, config_key, scope_type, scope_id, product_id, locale, value_json, schema_version, status, config_version, release_id, digest, updated_at FROM system_config_record WHERE status = 'active' AND (tenant_id IS NULL OR tenant_id = ?) ORDER BY id LIMIT ? OFFSET ?", [context.tenantId, Math.min(request.limit ?? 50, 100), offset]); const count = await client.query<Row>("SELECT COUNT(*) AS total FROM system_config_record WHERE status = 'active' AND (tenant_id IS NULL OR tenant_id = ?)", [context.tenantId]); return toPage(result.rows.map(mapConfig), offset, Number(count.rows[0]?.total ?? 0), request.limit); }); }
  public async upsert(context: TenantRequestContext, input: ConfigInput): Promise<SystemConfig> { return this.withTransaction(async (client) => { const tenantId = input.scopeType === "global" ? null : context.tenantId; const existing = await client.query<Row>("SELECT id, config_version FROM system_config_record WHERE status = 'active' AND ((tenant_id = ?) OR (tenant_id IS NULL AND ? IS NULL)) AND module_key = ? AND config_key = ? AND scope_type = ? AND ((scope_id = ?) OR (scope_id IS NULL AND ? IS NULL)) AND ((product_id = ?) OR (product_id IS NULL AND ? IS NULL)) AND ((locale = ?) OR (locale IS NULL AND ? IS NULL)) AND ((release_id = ?) OR (release_id IS NULL AND ? IS NULL)) LIMIT 1 FOR UPDATE", [tenantId, tenantId, input.moduleKey, input.configKey, input.scopeType, input.scopeId, input.scopeId, input.productId, input.productId, input.locale, input.locale, input.releaseId, input.releaseId]); const id = existing.rows[0] ? String(existing.rows[0].id) : randomUUID(); const configVersion = Number(existing.rows[0]?.config_version ?? 0) + 1; const time = timestamp(); const digest = createHash("sha256").update(JSON.stringify(input.value)).digest("hex"); if (existing.rows[0]) await client.query("UPDATE system_config_record SET schema_version = ?, value_json = ?, config_version = ?, digest = ?, updated_by = ?, updated_at = ? WHERE id = ?", [input.schemaVersion, JSON.stringify(input.value), configVersion, digest, context.actorId, time, id]); else await client.query("INSERT INTO system_config_record (id, tenant_id, module_key, scope_type, scope_id, product_id, locale, config_key, schema_version, value_json, status, config_version, release_id, digest, updated_by, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'active', ?, ?, ?, ?, ?, ?)", [id, tenantId, input.moduleKey, input.scopeType, input.scopeId, input.productId, input.locale, input.configKey, input.schemaVersion, JSON.stringify(input.value), configVersion, input.releaseId, digest, context.actorId, time, time]); return { id, tenantId, ...input, status: "active", configVersion, digest, updatedAt: time }; }); }
}
