import type { ConfigRelease, Site, SitePolicy, SystemConfig, Workspace } from "../../../modules/system/domain/models.js";
import type { Row } from "./support.js";
import { json, nullable, text } from "./support.js";

export function mapSite(row: Row): Site { return { id: text(row.id), tenantId: text(row.tenant_id), siteKey: text(row.site_key), hostnames: json(row.hostnames_json) as string[], displayName: text(row.display_name), status: text(row.status) as Site["status"], version: Number(row.version), createdAt: text(row.created_at), updatedAt: text(row.updated_at) }; }
export function mapWorkspace(row: Row): Workspace { return { id: text(row.id), tenantId: text(row.tenant_id), siteId: text(row.site_id), workspaceKey: text(row.workspace_key), name: text(row.name), status: text(row.status) as Workspace["status"], version: Number(row.version), createdAt: text(row.created_at), updatedAt: text(row.updated_at) }; }
export function mapPolicy(row: Row): SitePolicy { return { id: text(row.id), tenantId: text(row.tenant_id), siteId: text(row.site_id), version: Number(row.version), status: text(row.status) as SitePolicy["status"], defaultLocale: text(row.default_locale), allowedLocales: json(row.allowed_locales_json) as string[], allowedProducts: json(row.allowed_products_json) as string[], publicManifest: Boolean(row.public_manifest), updatedAt: text(row.updated_at) }; }
export function mapConfig(row: Row): SystemConfig { return { id: text(row.id), tenantId: nullable(row.tenant_id), moduleKey: text(row.module_key), configKey: text(row.config_key), scopeType: text(row.scope_type) as SystemConfig["scopeType"], scopeId: nullable(row.scope_id), productId: nullable(row.product_id), locale: nullable(row.locale), value: json(row.value_json), schemaVersion: Number(row.schema_version), status: text(row.status) as SystemConfig["status"], configVersion: Number(row.config_version), releaseId: nullable(row.release_id), digest: text(row.digest), updatedAt: text(row.updated_at) }; }
export function mapRelease(row: Row): ConfigRelease { return { id: text(row.id), tenantId: text(row.tenant_id), releaseKey: text(row.release_key), status: text(row.status) as ConfigRelease["status"], digest: text(row.digest), publishedAt: nullable(row.published_at), version: Number(row.version), createdAt: text(row.created_at), updatedAt: text(row.updated_at) }; }
