import { randomUUID } from "node:crypto";
import { createServer, type IncomingMessage, type Server, type ServerResponse } from "node:http";
import type { RuntimeManifestService } from "../../modules/runtime-manifest/service.js";
import type { TenantRequestContext } from "../../modules/runtime-manifest/model.js";
import type { TenantBindingVerifier } from "../../modules/runtime-manifest/ports.js";
import { SystemDomainError } from "../../modules/system/errors.js";
import type { ConfigInput, PageRequest, ReleaseInput, SiteInput, WorkspaceInput } from "../../modules/system/model.js";
import type { SystemControlService } from "../../modules/system/service.js";
import { requireBffServiceAuth, ServiceAuthError, ServiceAuthNotConfiguredError } from "./service-auth.js";

class RequestValidationError extends Error {}
type JsonRecord = Readonly<Record<string, unknown>>;
type HttpOptions = Readonly<{ control?: SystemControlService; binding?: TenantBindingVerifier; bffServiceToken?: string | null }>;

function send(response: ServerResponse, status: number, value: unknown, requestId: string): void { response.statusCode = status; response.setHeader("content-type", "application/json; charset=utf-8"); response.setHeader("x-kokoro-request-id", requestId); response.end(JSON.stringify(value)); }
function sendSuccess(response: ServerResponse, status: number, data: unknown, requestId: string): void { send(response, status, { data, meta: { request_id: requestId } }, requestId); }
function sendError(response: ServerResponse, status: number, code: string, message: string, requestId: string): void { send(response, status, { error: { code, message }, meta: { request_id: requestId } }, requestId); }
function requiredHeader(request: IncomingMessage, name: string): string { const value = request.headers[name]; if (typeof value !== "string" || value.trim() === "") throw new RequestValidationError(`${name} is required`); return value.trim(); }
function optionalHeader(request: IncomingMessage, name: string): string | null { const value = request.headers[name]; return typeof value === "string" && value.trim() ? value.trim() : null; }
function requiredQuery(url: URL, name: string): string { const value = url.searchParams.get(name); if (!value?.trim()) throw new RequestValidationError(`${name} is required`); return value.trim(); }
function context(request: IncomingMessage, requestId: string, surfaceId: string | null = null): TenantRequestContext { const permissionHeader = optionalHeader(request, "x-kokoro-iam-permissions"); return { tenantId: requiredHeader(request, "x-kokoro-tenant-id"), actorId: optionalHeader(request, "x-kokoro-actor-id"), organizationId: optionalHeader(request, "x-kokoro-organization-id"), surfaceId, permissions: permissionHeader ? permissionHeader.split(",").map((value) => value.trim()).filter(Boolean) : [], correlationId: requestId }; }
function idempotencyKey(request: IncomingMessage): string { return requiredHeader(request, "idempotency-key"); }
function jsonRecord(value: unknown): JsonRecord { if (typeof value !== "object" || value === null || Array.isArray(value)) throw new RequestValidationError("JSON body must be an object"); return value as JsonRecord; }
async function body(request: IncomingMessage): Promise<JsonRecord> { const chunks: Buffer[] = []; for await (const chunk of request) chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(String(chunk))); const raw = Buffer.concat(chunks); if (raw.length > 1_000_000) throw new RequestValidationError("request body is too large"); try { return jsonRecord(JSON.parse(raw.toString("utf8"))); } catch (error) { if (error instanceof RequestValidationError) throw error; throw new RequestValidationError("request body must be valid JSON"); } }
function stringField(input: JsonRecord, name: string): string { const value = input[name]; if (typeof value !== "string" || !value.trim()) throw new RequestValidationError(`${name} is required`); return value.trim(); }
function stringArray(input: JsonRecord, name: string): string[] { const value = input[name]; if (!Array.isArray(value) || value.some((item) => typeof item !== "string" || !item.trim())) throw new RequestValidationError(`${name} must be a string array`); return value.map((item) => String(item).trim()); }
function booleanField(input: JsonRecord, name: string): boolean { const value = input[name]; if (typeof value !== "boolean") throw new RequestValidationError(`${name} is required`); return value; }
function pageQuery(url: URL): PageRequest { const cursor = url.searchParams.get("cursor"); const limit = url.searchParams.get("limit"); return { ...(cursor === null ? {} : { cursor }), ...(limit === null ? {} : { limit: Number(limit) }) }; }
function controlRequired(control: SystemControlService | undefined): SystemControlService { if (!control) throw new SystemDomainError("NOT_IMPLEMENTED", "system control plane is not configured", 501); return control; }
function forwardedHost(request: IncomingMessage): string | null {
  const value = request.headers.forwarded;
  if (typeof value !== "string") return null;
  const match = /(?:^|;)\s*host=([^;\s,]+)/iu.exec(value.split(",", 1)[0] ?? "");
  return match?.[1]?.replace(/^"|"$/gu, "") ?? null;
}
function requestAuthority(request: IncomingMessage): string { return forwardedHost(request) ?? request.headers.host ?? ""; }

export function createHttpServer(service: RuntimeManifestService, readiness: () => Promise<boolean>, options: HttpOptions = {}): Server { return createServer(async (request, response) => { const requestId = optionalHeader(request, "x-kokoro-request-id") ?? randomUUID(); try { const url = new URL(request.url ?? "/", "http://localhost"); if (request.method === "GET" && url.pathname === "/healthz") return sendSuccess(response, 200, { status: "ok", service: "kokoro-system" }, requestId); if (request.method === "GET" && url.pathname === "/readyz") { try { const ready = await readiness(); return sendSuccess(response, ready ? 200 : 503, { status: ready ? "ready" : "not_ready", service: "kokoro-system" }, requestId); } catch { return sendError(response, 503, "SYSTEM_UNAVAILABLE", "system unavailable", requestId); } }
    const manifestRoute = url.pathname === "/system/runtime-manifest" || url.pathname === "/rpc/kokoro.system.v1.SystemService/GetRuntimeManifest";
    if (manifestRoute || url.pathname.startsWith("/system/")) requireBffServiceAuth(request, options.bffServiceToken);
    if ((request.method === "GET" || request.method === "POST") && manifestRoute) { const input = request.method === "POST" ? await body(request) : undefined; const productId = input ? stringField(input, "product_id") : requiredQuery(url, "product_id"); const locale = input ? (input.locale === undefined ? "en-US" : stringField(input, "locale")) : (url.searchParams.get("locale") ?? "en-US"); const surfaceId = input ? (input.surface_id === undefined ? null : stringField(input, "surface_id")) : (url.searchParams.get("surface_id") ?? null); const manifest = await service.get({ context: context(request, requestId, surfaceId), productId, locale, host: requestAuthority(request) }); return sendSuccess(response, 200, manifest, requestId); }
    const control = options.control;
    if (control && url.pathname.startsWith("/system/") && url.pathname !== "/system/runtime-manifest") { const requestContext = context(request, requestId); if (options.binding) await options.binding.verify({ context: requestContext, host: requestAuthority(request) }); else if (options.bffServiceToken?.trim()) throw new SystemDomainError("SERVICE_AUTH_NOT_CONFIGURED", "tenant binding verifier is not configured", 503); }
    if (request.method === "GET" && url.pathname === "/system/sites") return sendSuccess(response, 200, await controlRequired(control).listSites(context(request, requestId), pageQuery(url)), requestId);
    if (request.method === "POST" && url.pathname === "/system/sites") { const input = await body(request); const value: SiteInput = { siteKey: stringField(input, "site_key"), hostname: stringField(input, "hostname"), displayName: stringField(input, "display_name") }; return sendSuccess(response, 201, await controlRequired(control).createSite(context(request, requestId), value, idempotencyKey(request)), requestId); }
    if (request.method === "GET" && url.pathname === "/system/workspaces") return sendSuccess(response, 200, await controlRequired(control).listWorkspaces(context(request, requestId), pageQuery(url)), requestId);
    if (request.method === "POST" && url.pathname === "/system/workspaces") { const input = await body(request); const value: WorkspaceInput = { siteId: stringField(input, "site_id"), workspaceKey: stringField(input, "workspace_key"), name: stringField(input, "name") }; return sendSuccess(response, 201, await controlRequired(control).createWorkspace(context(request, requestId), value, idempotencyKey(request)), requestId); }
    const policy = /^\/system\/sites\/([^/]+)\/policy$/u.exec(url.pathname);
    if (policy && request.method === "GET") return sendSuccess(response, 200, await controlRequired(control).getPolicy(context(request, requestId), policy[1] ?? ""), requestId);
    if (policy && request.method === "PUT") { const input = await body(request); const value = { version: 1, status: "active" as const, defaultLocale: stringField(input, "default_locale"), allowedLocales: stringArray(input, "allowed_locales"), allowedProducts: stringArray(input, "allowed_products"), publicManifest: booleanField(input, "public_manifest") }; return sendSuccess(response, 200, await controlRequired(control).putPolicy(context(request, requestId), policy[1] ?? "", value, idempotencyKey(request)), requestId); }
    if (request.method === "POST" && url.pathname === "/system/releases") { const input = await body(request); const value: ReleaseInput = { releaseKey: stringField(input, "release_key"), digest: stringField(input, "digest") }; return sendSuccess(response, 201, await controlRequired(control).createRelease(context(request, requestId), value, idempotencyKey(request)), requestId); }
    if (request.method === "GET" && url.pathname === "/system/config") return sendSuccess(response, 200, await controlRequired(control).listConfigs(context(request, requestId), pageQuery(url)), requestId);
    if (request.method === "POST" && url.pathname === "/system/config") { const input = await body(request); const scopeType = stringField(input, "scope_type"); if (!["global", "tenant", "product", "surface"].includes(scopeType)) throw new RequestValidationError("scope_type is invalid"); const schemaVersion = input.schema_version; if (typeof schemaVersion !== "number" || !Number.isInteger(schemaVersion) || schemaVersion < 1) throw new RequestValidationError("schema_version is invalid"); const value: ConfigInput = { moduleKey: stringField(input, "module_key"), configKey: stringField(input, "config_key"), scopeType: scopeType as ConfigInput["scopeType"], scopeId: typeof input.scope_id === "string" ? input.scope_id : null, productId: typeof input.product_id === "string" ? input.product_id : null, locale: typeof input.locale === "string" ? input.locale : null, value: input.value, schemaVersion, releaseId: typeof input.release_id === "string" ? input.release_id : null }; return sendSuccess(response, 201, await controlRequired(control).upsertConfig(context(request, requestId), value, idempotencyKey(request)), requestId); }
    const release = /^\/system\/releases\/([^/]+)\/(validate|publish|retire)$/u.exec(url.pathname);
    if (release && request.method === "POST") { const id = release[1] ?? ""; const key = idempotencyKey(request); const target = release[2]; const value = target === "validate" ? await controlRequired(control).validateRelease(context(request, requestId), id, key) : target === "publish" ? await controlRequired(control).publishRelease(context(request, requestId), id, key) : await controlRequired(control).retireRelease(context(request, requestId), id, key); return sendSuccess(response, 200, value, requestId); }
    return sendError(response, 404, "not_found", "not found", requestId);
  } catch (error) { if (error instanceof RequestValidationError) return sendError(response, 400, "INVALID_ARGUMENT", error.message, requestId); if (error instanceof ServiceAuthNotConfiguredError) return sendError(response, error.status, error.code, error.message, requestId); if (error instanceof ServiceAuthError) return sendError(response, error.status, error.code, error.message, requestId); if (error instanceof SystemDomainError) return sendError(response, error.status, error.code, error.message, requestId); return sendError(response, 503, "SYSTEM_UNAVAILABLE", "system unavailable", requestId); } }); }
