import { createHash, randomUUID } from "node:crypto";
import type { SqlClient, SqlPool } from "./client.js";
import type { TenantRequestContext } from "../../modules/runtime-manifest/model.js";
import { SystemDomainError } from "../../modules/system/errors.js";
import type { ConfigInput, ConfigRelease, Page, PageRequest, ReleaseInput, Site, SiteInput, SitePolicy, SystemConfig, SystemControlRepository, Workspace, WorkspaceInput } from "../../modules/system/model.js";

type Row = Record<string, unknown>;
const timestamp = (): string => new Date().toISOString();
const text = (value: unknown): string => String(value);
const nullable = (value: unknown): string | null => value === null || value === undefined ? null : String(value);
const json = (value: unknown): unknown => typeof value === "string" ? JSON.parse(value) as unknown : value;
function cursorOffset(request: PageRequest): number { if (!request.cursor) return 0; const value = Number.parseInt(Buffer.from(request.cursor, "base64url").toString("utf8"), 10); if (!Number.isInteger(value) || value < 0) throw new SystemDomainError("INVALID_CURSOR", "cursor is invalid"); return value; }
function toPage<T>(items: readonly T[], offset: number, total: number, limit = 50): Page<T> { const size = Math.min(Math.max(limit, 1), 100); return { items: items.slice(0, size), nextCursor: offset + items.length < total ? Buffer.from(String(offset + items.length)).toString("base64url") : null }; }
function requireRow<T>(row: T | undefined, message: string): T { if (!row) throw new SystemDomainError("NOT_FOUND", message, 404); return row; }

export class PostgresSystemControlRepository implements SystemControlRepository {
  public constructor(private readonly pool: SqlPool) {}
  private async withClient<T>(operation: (client: SqlClient) => Promise<T>): Promise<T> { const client = await this.pool.connect(); try { await client.query("START TRANSACTION"); const result = await operation(client); await client.query("COMMIT"); return result; } catch (error) { try { await client.query("ROLLBACK"); } catch { /* preserve the original database error */ } throw error; } finally { client.release(); } }
  public async listSites(context: TenantRequestContext, request: PageRequest): Promise<Page<Site>> { return this.withClient(async (client) => { const offset = cursorOffset(request); const result = await client.query<Row>("SELECT id, tenant_id, site_key, hostnames_json, display_name, status, version, created_at, updated_at FROM system_site WHERE tenant_id = ? AND status <> 'archived' ORDER BY id LIMIT ? OFFSET ?", [context.tenantId, Math.min(request.limit ?? 50, 100), offset]); const count = await client.query<Row>("SELECT COUNT(*) AS total FROM system_site WHERE tenant_id = ? AND status <> 'archived'", [context.tenantId]); return toPage(result.rows.map(site), offset, Number(count.rows[0]?.total ?? 0), request.limit); }); }
  public async createSite(context: TenantRequestContext, input: SiteInput): Promise<Site> { return this.withClient(async (client) => { const duplicate = await client.query<Row>("SELECT id FROM system_site WHERE tenant_id = ? AND site_key = ? AND status <> 'archived' LIMIT 1", [context.tenantId, input.siteKey]); if (duplicate.rows.length) throw new SystemDomainError("CONFLICT", "site_key already exists", 409); const id = randomUUID(); const time = timestamp(); await client.query("INSERT INTO system_site (id, tenant_id, site_key, hostnames_json, display_name, status, version, created_at, updated_at) VALUES (?, ?, ?, ?, ?, 'active', 1, ?, ?)", [id, context.tenantId, input.siteKey, JSON.stringify([input.hostname]), input.displayName, time, time]); return { id, tenantId: context.tenantId, siteKey: input.siteKey, hostnames: [input.hostname], displayName: input.displayName, status: "active", version: 1, createdAt: time, updatedAt: time }; }); }
  public async listWorkspaces(context: TenantRequestContext, request: PageRequest): Promise<Page<Workspace>> { return this.withClient(async (client) => { const offset = cursorOffset(request); const result = await client.query<Row>("SELECT id, tenant_id, site_id, workspace_key, name, status, version, created_at, updated_at FROM system_workspace WHERE tenant_id = ? AND status <> 'archived' ORDER BY id LIMIT ? OFFSET ?", [context.tenantId, Math.min(request.limit ?? 50, 100), offset]); const count = await client.query<Row>("SELECT COUNT(*) AS total FROM system_workspace WHERE tenant_id = ? AND status <> 'archived'", [context.tenantId]); return toPage(result.rows.map(workspace), offset, Number(count.rows[0]?.total ?? 0), request.limit); }); }
  public async createWorkspace(context: TenantRequestContext, input: WorkspaceInput): Promise<Workspace> { return this.withClient(async (client) => { const site = await client.query<Row>("SELECT id FROM system_site WHERE id = ? AND tenant_id = ? AND status <> 'archived' LIMIT 1", [input.siteId, context.tenantId]); requireRow(site.rows[0], "site not found"); const duplicate = await client.query<Row>("SELECT id FROM system_workspace WHERE tenant_id = ? AND site_id = ? AND workspace_key = ? AND status <> 'archived' LIMIT 1", [context.tenantId, input.siteId, input.workspaceKey]); if (duplicate.rows.length) throw new SystemDomainError("CONFLICT", "workspace_key already exists", 409); const id = randomUUID(); const time = timestamp(); await client.query("INSERT INTO system_workspace (id, tenant_id, site_id, workspace_key, name, status, version, created_at, updated_at) VALUES (?, ?, ?, ?, ?, 'active', 1, ?, ?)", [id, context.tenantId, input.siteId, input.workspaceKey, input.name, time, time]); return { id, tenantId: context.tenantId, siteId: input.siteId, workspaceKey: input.workspaceKey, name: input.name, status: "active", version: 1, createdAt: time, updatedAt: time }; }); }
  public async getPolicy(context: TenantRequestContext, siteId: string): Promise<SitePolicy | null> { return this.withClient(async (client) => { const result = await client.query<Row>("SELECT id, tenant_id, site_id, version, status, default_locale, allowed_locales_json, allowed_products_json, public_manifest, updated_at FROM system_site_policy WHERE site_id = ? AND tenant_id = ? AND status = 'active' LIMIT 1", [siteId, context.tenantId]); return result.rows[0] ? policy(result.rows[0]) : null; }); }
  public async putPolicy(context: TenantRequestContext, siteId: string, input: Omit<SitePolicy, "id" | "tenantId" | "siteId" | "updatedAt">): Promise<SitePolicy> { return this.withClient(async (client) => { const site = await client.query<Row>("SELECT id FROM system_site WHERE id = ? AND tenant_id = ? LIMIT 1", [siteId, context.tenantId]); requireRow(site.rows[0], "site not found"); const old = await client.query<Row>("SELECT id, version FROM system_site_policy WHERE site_id = ? AND tenant_id = ? AND status = 'active' LIMIT 1", [siteId, context.tenantId]); const id = old.rows[0] ? text(old.rows[0].id) : randomUUID(); const version = Number(old.rows[0]?.version ?? 0) + 1; const time = timestamp(); if (old.rows[0]) await client.query("UPDATE system_site_policy SET status = 'archived', updated_at = ? WHERE id = ?", [time, id]); await client.query("INSERT INTO system_site_policy (id, tenant_id, site_id, version, status, default_locale, allowed_locales_json, allowed_products_json, public_manifest, updated_at) VALUES (?, ?, ?, ?, 'active', ?, ?, ?, ?, ?)", [id, context.tenantId, siteId, version, input.defaultLocale, JSON.stringify(input.allowedLocales), JSON.stringify(input.allowedProducts), input.publicManifest, time]); return { ...input, id, tenantId: context.tenantId, siteId, version, updatedAt: time }; }); }
  public async createRelease(context: TenantRequestContext, input: ReleaseInput): Promise<ConfigRelease> { return this.withClient(async (client) => { const duplicate = await client.query<Row>("SELECT id FROM system_config_release WHERE tenant_id = ? AND release_key = ? AND status <> 'retired' LIMIT 1 FOR UPDATE", [context.tenantId, input.releaseKey]); if (duplicate.rows.length) throw new SystemDomainError("CONFLICT", "release_key already exists", 409); const id = randomUUID(); const time = timestamp(); await client.query("INSERT INTO system_config_release (id, tenant_id, release_key, status, digest, published_at, version, created_at, updated_at) VALUES (?, ?, ?, 'draft', ?, NULL, 1, ?, ?)", [id, context.tenantId, input.releaseKey, input.digest, time, time]); return { id, tenantId: context.tenantId, releaseKey: input.releaseKey, status: "draft", digest: input.digest, publishedAt: null, version: 1, createdAt: time, updatedAt: time }; }); }
  public async listConfigs(context: TenantRequestContext, request: PageRequest): Promise<Page<SystemConfig>> { return this.withClient(async (client) => { const offset = cursorOffset(request); const result = await client.query<Row>("SELECT id, tenant_id, module_key, config_key, scope_type, scope_id, product_id, locale, value_json, schema_version, status, config_version, release_id, digest, updated_at FROM system_config_record WHERE status = 'active' AND (tenant_id IS NULL OR tenant_id = ?) ORDER BY id LIMIT ? OFFSET ?", [context.tenantId, Math.min(request.limit ?? 50, 100), offset]); const count = await client.query<Row>("SELECT COUNT(*) AS total FROM system_config_record WHERE status = 'active' AND (tenant_id IS NULL OR tenant_id = ?)", [context.tenantId]); return toPage(result.rows.map(config), offset, Number(count.rows[0]?.total ?? 0), request.limit); }); }
  public async upsertConfig(context: TenantRequestContext, input: ConfigInput): Promise<SystemConfig> { return this.withClient(async (client) => { const tenantId = input.scopeType === "global" ? null : context.tenantId; const existing = await client.query<Row>("SELECT id, config_version FROM system_config_record WHERE status = 'active' AND ((tenant_id = ?) OR (tenant_id IS NULL AND ? IS NULL)) AND module_key = ? AND config_key = ? AND scope_type = ? AND ((scope_id = ?) OR (scope_id IS NULL AND ? IS NULL)) AND ((product_id = ?) OR (product_id IS NULL AND ? IS NULL)) AND ((locale = ?) OR (locale IS NULL AND ? IS NULL)) AND ((release_id = ?) OR (release_id IS NULL AND ? IS NULL)) LIMIT 1 FOR UPDATE", [tenantId, tenantId, input.moduleKey, input.configKey, input.scopeType, input.scopeId, input.scopeId, input.productId, input.productId, input.locale, input.locale, input.releaseId, input.releaseId]); const id = existing.rows[0] ? text(existing.rows[0].id) : randomUUID(); const configVersion = Number(existing.rows[0]?.config_version ?? 0) + 1; const time = timestamp(); const digest = createHash("sha256").update(JSON.stringify(input.value)).digest("hex"); if (existing.rows[0]) await client.query("UPDATE system_config_record SET schema_version = ?, value_json = ?, config_version = ?, digest = ?, updated_by = ?, updated_at = ? WHERE id = ?", [input.schemaVersion, JSON.stringify(input.value), configVersion, digest, context.actorId, time, id]); else await client.query("INSERT INTO system_config_record (id, tenant_id, module_key, scope_type, scope_id, product_id, locale, config_key, schema_version, value_json, status, config_version, release_id, digest, updated_by, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'active', ?, ?, ?, ?, ?, ?)", [id, tenantId, input.moduleKey, input.scopeType, input.scopeId, input.productId, input.locale, input.configKey, input.schemaVersion, JSON.stringify(input.value), configVersion, input.releaseId, digest, context.actorId, time, time]); return { id, tenantId, ...input, status: "active", configVersion, digest, updatedAt: time }; }); }
  public async getRelease(context: TenantRequestContext, releaseId: string): Promise<ConfigRelease | null> { return this.withClient(async (client) => { const result = await client.query<Row>("SELECT id, tenant_id, release_key, status, digest, published_at, version, created_at, updated_at FROM system_config_release WHERE id = ? AND tenant_id = ? LIMIT 1", [releaseId, context.tenantId]); return result.rows[0] ? release(result.rows[0]) : null; }); }
  public async updateRelease(context: TenantRequestContext, releaseId: string, status: ConfigRelease["status"]): Promise<ConfigRelease> { return this.withClient(async (client) => { const current = requireRow((await client.query<Row>("SELECT id, tenant_id, release_key, status, digest, published_at, version, created_at, updated_at FROM system_config_release WHERE id = ? AND tenant_id = ? LIMIT 1", [releaseId, context.tenantId])).rows[0], "release not found"); const time = timestamp(); await client.query("UPDATE system_config_release SET status = ?, published_at = ?, version = version + 1, updated_at = ? WHERE id = ? AND tenant_id = ?", [status, status === "published" ? time : current.published_at ?? null, time, releaseId, context.tenantId]); return release({ ...current, status, published_at: status === "published" ? time : current.published_at, version: Number(current.version) + 1, updated_at: time }); }); }
  public async getReceipt(tenantId: string, key: string): Promise<Readonly<{ requestHash: string; response: unknown }> | null> { return this.withClient(async (client) => { const result = await client.query<Row>("SELECT request_hash, response_json FROM system_command_receipt WHERE tenant_id = ? AND idempotency_key = ? ORDER BY created_at DESC, id DESC LIMIT 1", [tenantId, key]); const row = result.rows[0]; return row ? { requestHash: text(row.request_hash), response: json(row.response_json) } : null; }); }
  public async saveReceipt(tenantId: string, key: string, requestHash: string, response: unknown): Promise<void> { await this.withClient(async (client) => { await client.query("INSERT INTO system_command_receipt (id, tenant_id, idempotency_key, request_hash, response_json, created_at) VALUES (?, ?, ?, ?, ?, ?)", [randomUUID(), tenantId, key, requestHash, JSON.stringify(response), timestamp()]); }); }
}

function site(row: Row): Site { return { id: text(row.id), tenantId: text(row.tenant_id), siteKey: text(row.site_key), hostnames: json(row.hostnames_json) as string[], displayName: text(row.display_name), status: text(row.status) as Site["status"], version: Number(row.version), createdAt: text(row.created_at), updatedAt: text(row.updated_at) }; }
function workspace(row: Row): Workspace { return { id: text(row.id), tenantId: text(row.tenant_id), siteId: text(row.site_id), workspaceKey: text(row.workspace_key), name: text(row.name), status: text(row.status) as Workspace["status"], version: Number(row.version), createdAt: text(row.created_at), updatedAt: text(row.updated_at) }; }
function policy(row: Row): SitePolicy { return { id: text(row.id), tenantId: text(row.tenant_id), siteId: text(row.site_id), version: Number(row.version), status: text(row.status) as SitePolicy["status"], defaultLocale: text(row.default_locale), allowedLocales: json(row.allowed_locales_json) as string[], allowedProducts: json(row.allowed_products_json) as string[], publicManifest: Boolean(row.public_manifest), updatedAt: text(row.updated_at) }; }
function config(row: Row): SystemConfig { return { id: text(row.id), tenantId: nullable(row.tenant_id), moduleKey: text(row.module_key), configKey: text(row.config_key), scopeType: text(row.scope_type) as SystemConfig["scopeType"], scopeId: nullable(row.scope_id), productId: nullable(row.product_id), locale: nullable(row.locale), value: json(row.value_json), schemaVersion: Number(row.schema_version), status: text(row.status) as SystemConfig["status"], configVersion: Number(row.config_version), releaseId: nullable(row.release_id), digest: text(row.digest), updatedAt: text(row.updated_at) }; }
function release(row: Row): ConfigRelease { return { id: text(row.id), tenantId: text(row.tenant_id), releaseKey: text(row.release_key), status: text(row.status) as ConfigRelease["status"], digest: text(row.digest), publishedAt: nullable(row.published_at), version: Number(row.version), createdAt: text(row.created_at), updatedAt: text(row.updated_at) }; }
